package(default_visibility = ["//visibility:public"])

pex_library(
    name = "common-py",
    srcs = glob(["**/*.py"]),
    reqs = [
        "colorlog==6.10.1",
    ],
    deps = [
        "//heron/proto:proto-py",
    ],
)
